package luna.ui;

import java.util.Scanner;

/**
 * Handles command-line input and output for Luna.
 * The JavaFX interface uses its own controls for input and output.
 */
public class Ui {
    private static final String LINE = "____________________________________________________________\n";
    private final Scanner scanner;

    /**
     * Creates a Ui instance that reads from standard input.
     */
    public Ui() {
        this.scanner = new Scanner(System.in);
    }

    /**
     * Prints the horizontal separator line.
     */
    public void showLine() {
        System.out.println(LINE);
    }

    /**
     * Shows the welcome message.
     */
    public void showWelcome() {
        System.out.println("Hello! I'm Luna");
        System.out.println("What can I do for you?\n");
    }

    /**
     * Shows an error message.
     *
     * @param message Error message to show.
     */
    public void showError(String message) {
        System.out.println(message);
    }

    /**
     * Prints a response generated by Luna.
     *
     * @param response Response to print.
     */
    public void showResponse(String response) {
        System.out.println(response);
    }

    /**
     * Reads the next line of user input (trimmed).
     *
     * @return User input as a trimmed string.
     */
    public String readCommand() {
        return scanner.nextLine().trim();
    }

    /**
     * Closes the underlying scanner.
     * Call this when the program is exiting.
     */
    public void close() {
        scanner.close();
    }
}
